### ISSUE TITLE
write to PDF 

### ISSUE THREAD

**Issue by niekverw** [rdboyes/forestable#1]
Fantastic work!  there aren't any good packages for forest plots, this looks great. 
Is it possible to output a  PDF instead of PNG ? 

Best, niek

**Comment by rdboyes** [comment]
Hi Niek, 

Currently, the best way to output to PDF is to output to png, then include the image in a RMarkdown file using standard markdown syntax (e.g. `![](file.png)`) and pdf_document as the target format.

**Comment by niekverw** [comment]
Thanks, but that defeats the purpose of a pdf :). 
Looking at the code I can see the difficulty of properly implementing pdf.

**Comment by rdboyes** [comment]
Ah I see what you're saying. Maybe one day I'll figure out how to correctly support PDF, but for now I've got enough trouble just making everything line up in the png output :)
