### ISSUE TITLE
How can I change the decimal point in the confidence interval to two digits?

### ISSUE THREAD

**Issue by YukiSahashi** [rdboyes/forestable#2]
Hi, Dr. Boyes

I am Yuki Sahashi from Gifu Univ. I found the fantastic R-package “forestable” which you made.
I am struggling with change something. 

How can I change the decimal point in the confidence interval to two digits?

Best,
Yuki

**Comment by rdboyes** [comment]
Hi Yuki, 

There is a parameter in the function called `estimate_precision` which defaults to 1 but can be changed to 2
